name: "Lint"

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node from node version file
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install correct npm version
        run: npm install -g npm@^10
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint